version: "3"

services:
        nginx:
                build: ./requirements/nginx
                container_name: nginx
                restart: always
                ports:
                        - "443:443"
                depends_on:
                        - wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - inception-net
        mariadb:
                build: ./requirements/mariadb
                container_name: mariadb
                restart: always
                env_file: .env
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - inception-net
        wordpress:
                build: ./requirements/wordpress
                container_name: wordpress
                restart: always
                env_file: .env
                depends_on:
                        - mariadb
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - inception-net

networks:
        inception-net:

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/eerika/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/eerika/data/mariadb
                        o: bind
                        type: none